Update grpc to 1.29.1
Needed to fix gcc-9.2.1-31 compilation issue:

external/com_github_grpc_grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1105:13: error: ambiguating new declaration of 'long int gettid()'

The fix on grpc side is: https://github.com/grpc/grpc/commit/de6255941a5e1c2fb2d50e57f84e38c09f45023d
Update to the latest grpc to get that fix in.